# Generated by Django 3.1.3 on 2021-04-22 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 7, 29, 18, 54233, tzinfo=utc)),
        ),
    ]
