# Generated by Django 3.1.7 on 2021-04-23 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210422_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 8, 13, 50, 96952, tzinfo=utc)),
        ),
    ]
