# Generated by Django 3.1.7 on 2021-04-26 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210423_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 3, 10, 48, 178404, tzinfo=utc)),
        ),
    ]
