# Generated by Django 3.1.7 on 2021-04-30 02:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210430_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 2, 46, 15, 821427, tzinfo=utc)),
        ),
    ]
