# Generated by Django 3.1.7 on 2021-04-27 02:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210426_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 2, 16, 25, 506043, tzinfo=utc)),
        ),
    ]
