# Generated by Django 3.1.7 on 2021-04-27 06:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20210427_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 6, 57, 16, 870344, tzinfo=utc)),
        ),
    ]
