# Generated by Django 3.1.7 on 2021-04-28 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20210427_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 7, 46, 41, 276639, tzinfo=utc)),
        ),
    ]
