# Generated by Django 3.1.7 on 2021-04-28 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20210428_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 13, 13, 46, 793152, tzinfo=utc)),
        ),
    ]
