# Generated by Django 3.1.7 on 2021-04-28 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20210428_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 13, 50, 53, 510912, tzinfo=utc)),
        ),
    ]
