# Generated by Django 3.1.7 on 2021-04-29 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20210428_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 16, 39, 43, 263021, tzinfo=utc)),
        ),
    ]
