# Generated by Django 3.1.7 on 2021-04-29 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20210429_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 18, 35, 33, 798078, tzinfo=utc)),
        ),
    ]
